name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Tidy
        run: go mod tidy
      - name: Build
        run: go build -v ./...
      - name: Functional test (local server)
        run: go test -v -run TestFunctional -args -duration=2s

